"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import AppShell, { ButtonArrow, SectionHeading } from "@/components/AppShell";
import { useLanguage } from "@/components/LanguageProvider";

type Message = { id: string; channel: string; subject: string | null; body: string; due_at: string | null; sent_at: string | null; created_at: string; prospects: { name?: string; status?: string; best_channel?: string } | null };

export default function SendPage() {
  const { text } = useLanguage(); const [messages, setMessages] = useState<Message[]>([]); const [loading, setLoading] = useState(true); const [copied, setCopied] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { fetch("/api/messages", { cache: "no-store" }).then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error(body.detail); setMessages(body.messages ?? []); }).catch((cause) => setError(cause instanceof Error ? cause.message : text("Could not load messages", "No se pudieron cargar los mensajes"))).finally(() => setLoading(false)); }, [text]);
  async function copy(message: Message) { await navigator.clipboard.writeText(message.body); setCopied(message.id); }
  return <AppShell><div className="page-toolbar"><SectionHeading eyebrow={text("Outreach / controlled send", "Contacto / envío controlado")} title={text("Every message stays human-approved.", "Cada mensaje requiere aprobación humana.")} detail={text("Only messages stored for the active company appear here. AnimaRadar does not send them automatically.", "Aquí solo aparecen mensajes guardados para la empresa activa. AnimaRadar no los envía automáticamente.")} /><ButtonArrow href="/prospectos">{text("Back to review", "Volver a revisión")}</ButtonArrow></div>{error && <p className="error" aria-live="polite">{error}</p>}<section className="panel"><div className="panel-title"><h2>{text("Prepared messages", "Mensajes preparados")}</h2><span className="live-label">{messages.length} {text("ready", "listos")}</span></div>{loading ? <div className="empty-state">{text("Loading messages…", "Cargando mensajes…")}</div> : messages.length ? <div className="activity-list">{messages.map((message) => <article className="activity-row" key={message.id}><span className="activity-icon">{message.prospects?.name?.slice(0, 1) ?? "M"}</span><div className="message-record"><p><strong>{message.prospects?.name ?? text("Unknown prospect", "Prospecto desconocido")}</strong></p><small>{message.channel} · {message.sent_at ? text("sent", "enviado") : text("not sent", "no enviado")}</small>{message.subject && <h3>{message.subject}</h3>}<p className="message-preview">{message.body}</p><button className="button button-ghost" onClick={() => copy(message)}>{copied === message.id ? text("Copied", "Copiado") : text("Copy message", "Copiar mensaje")}</button></div></article>)}</div> : <div className="empty-state empty-state--action"><strong>{text("No prepared messages yet.", "Aún no hay mensajes preparados.")}</strong><p>{text("Approve a real prospect first. Message drafts created for that prospect will appear here.", "Aprueba primero un prospecto real. Los borradores creados para ese prospecto aparecerán aquí.")}</p><Link href="/prospectos">{text("Open prospect review", "Abrir revisión de prospectos")} ↗</Link></div>}</section></AppShell>;
}
