"use client";
import { useState } from "react";
import AppShell, { SectionHeading } from "@/components/AppShell";

const features = [
  ["Business DNA", "Define offer, fit, proof and exclusions.", "ready"],
  ["Radar scans", "Discover and queue businesses by market and radius.", "partial"],
  ["Evidence & scoring", "Keep sourced evidence separate from hypotheses.", "partial"],
  ["Human review", "Approve or discard before any outreach.", "ready"],
  ["Outreach", "Open the approved channel and keep the sender human.", "partial"],
  ["Learning Loop", "Record outcomes and improve future scans.", "planned"],
] as const;

export default function SettingsPage() {
  const [saved, setSaved] = useState(false);
  return <AppShell><div className="page-toolbar"><SectionHeading eyebrow="Settings / readiness" title="Make the workspace yours." detail="Settings is the control room for tenant identity, data sources, sending rules and the path from demo data to live use." /><span className="feature-status feature-status--partial">Live readiness: 40%</span></div><div className="settings-grid"><section className="panel settings-card"><div className="panel-title"><h2>Workspace identity</h2><span className="feature-status feature-status--ready">Connected</span></div><div className="settings-fields"><label>Workspace name<input defaultValue="Andes Bloom" /></label><label>Market language<select defaultValue="en-CA"><option value="en-CA">English · Canada</option><option value="de-DE">Deutsch · Germany</option><option value="ru-RU">Русский</option></select></label><label>Default market<input defaultValue="Vancouver, Canada" /></label><button className="button button-primary" onClick={()=>setSaved(true)}>{saved?"Saved":"Save workspace"}<span className="button-arrow" aria-hidden="true" /></button></div>{saved&&<p className="notice" aria-live="polite">Workspace settings are staged locally. Persistence requires the authenticated Supabase tenant.</p>}</section><section className="panel settings-card"><div className="panel-title"><h2>Connections</h2><span className="feature-status feature-status--partial">Needs setup</span></div><div className="connection-list"><div><span className="connection-dot connection-dot--ready"/><div><strong>Supabase</strong><small>Schema and tenant isolation are prepared.</small></div><b>Schema ready</b></div><div><span className="connection-dot"/><div><strong>Discovery providers</strong><small>Google Places / Exa keys are not verified in this workspace.</small></div><b>Not verified</b></div><div><span className="connection-dot"/><div><strong>Authenticated API</strong><small>Current web proxy falls back to a local API URL.</small></div><b>Required</b></div></div></section></div><section className="panel feature-matrix"><div className="panel-title"><h2>Feature map</h2><span>What is available today</span></div>{features.map(([name,description,status])=><div className="feature-row" key={name}><div><strong>{name}</strong><small>{description}</small></div><span className={`feature-status feature-status--${status}`}>{status==="ready"?"Available":status==="partial"?"Partial":"Next build"}</span></div>)}</section><section className="readiness-note"><div><p className="eyebrow">Before you go live</p><h2>Connect identity, providers and persistence.</h2></div><p>To use AnimaRadar with your own company, the next release must authenticate the owner, resolve the tenant from the JWT, route the web app to a deployed API, and replace sample prospect/outreach records with Supabase reads and writes.</p></section></AppShell>;
}
