"use client";
import { useState } from "react";
import AppShell, { SectionHeading } from "@/components/AppShell";

const outcomes = [
  ["Reply", "Did the business respond?", "A reply is the first learning signal."],
  ["Interest", "Was there qualified interest?", "Separate curiosity from a real buying conversation."],
  ["Result", "What happened commercially?", "Meetings, proposals, orders and losses improve the next scan."],
] as const;

export default function LearningLoopPage() {
  const [selected, setSelected] = useState<string | null>(null);
  return <AppShell><div className="page-toolbar"><SectionHeading eyebrow="Learning loop / outcomes" title="Turn conversations into a sharper radar." detail="Learning Loop is not another overview. It records what happened after a human-approved message so future scoring can improve." /><span className="feature-status feature-status--preview">Preview until live outcomes are connected</span></div><div className="learning-layout"><section className="panel learning-hero"><p className="eyebrow">What the system learns</p><h2>Evidence gets stronger<br/><em>when outcomes come back.</em></h2><p>Every approved outreach can become a feedback signal. The operator stays in control: AnimaRadar never silently treats an unanswered message as a win.</p><div className="learning-path"><span>Observed signal</span><i>→</i><span>Human decision</span><i>→</i><span>Business outcome</span></div></section><section className="panel learning-progress"><div className="panel-title"><h2>Current learning surface</h2><span className="feature-status feature-status--preview">Demo data</span></div><div className="learning-stat"><strong>02</strong><span>outcomes ready to review</span></div><div className="learning-stat"><strong>07</strong><span>approved messages in the sample queue</span></div><div className="learning-stat"><strong>0</strong><span>live outcome events connected</span></div></section></div><section className="outcome-grid"><div className="section-mini"><p className="eyebrow">Outcome capture</p><h2>Define the next truth.</h2><p>These are the chores the operator completes after outreach. They create the feedback needed for the learning loop.</p></div>{outcomes.map(([label,title,detail])=><button className={`outcome-card ${selected===label?"is-selected":""}`} key={label} onClick={()=>setSelected(label)}><span className="outcome-number">0{outcomes.findIndex(item=>item[0]===label)+1}</span><strong>{title}</strong><small>{detail}</small><span className="outcome-action">{selected===label?"Marked for setup":"Explore outcome"}<b>↗</b></span></button>)}</section>{selected&&<p className="notice" aria-live="polite">“{selected}” is marked for setup. Live outcome capture will be enabled after Supabase Auth and message records are connected.</p>}<section className="feature-strip"><div><p className="eyebrow">Why this exists</p><h2>Learning Loop closes the promise.</h2></div><p>Without outcomes, the radar can discover and score prospects, but it cannot honestly learn which signals led to replies, meetings or orders. This page is the operator’s review surface for that missing layer.</p></section></AppShell>;
}
