"use client";

import Link from "next/link";
import type { Route } from "next";
import { FormEvent, useEffect, useState } from "react";
import AppShell, { SectionHeading } from "@/components/AppShell";

type Company = { id: string; name: string };
type Credentials = { login: string; temporary_password: string; full_name: string };

export default function AdminUsersPage() {
  const [fullName, setFullName] = useState(""); const [companyId, setCompanyId] = useState(""); const [companies, setCompanies] = useState<Company[]>([]); const [credentials, setCredentials] = useState<Credentials | null>(null); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false); const [copied, setCopied] = useState(false);
  useEffect(() => { fetch("/api/admin/tenants").then(async (response) => { const body = await response.json() as { tenants?: Company[]; detail?: string }; if (!response.ok) throw new Error(body.detail ?? "Companies could not be loaded"); setCompanies(body.tenants ?? []); if (body.tenants?.[0]) setCompanyId(body.tenants[0].id); }).catch((cause) => setError(cause instanceof Error ? cause.message : "Companies could not be loaded")); }, []);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(null); setCredentials(null); setCopied(false); try { const response = await fetch("/api/admin/users", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ full_name: fullName, tenant_id: companyId }) }); const body = await response.json() as { detail?: string; login?: string; temporary_password?: string; full_name?: string }; if (!response.ok || !body.login || !body.temporary_password || !body.full_name) throw new Error(body.detail ?? "User could not be created"); setCredentials({ login: body.login, temporary_password: body.temporary_password, full_name: body.full_name }); setFullName(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "User could not be created"); } finally { setSaving(false); } }
  async function copyCredentials() { if (!credentials) return; await navigator.clipboard.writeText(`AnimaRadar login\nName: ${credentials.full_name}\nLogin ID: ${credentials.login}\nTemporary password: ${credentials.temporary_password}`); setCopied(true); }
  return <AppShell><div className="admin-page"><div className="page-toolbar"><SectionHeading title="Users" detail="Create a login and assign the user to a company." /><Link href={"/admin/companies" as Route} className="button button-ghost">View companies<span className="button-arrow" aria-hidden="true"/></Link></div><div className="admin-layout"><section className="panel admin-create"><h2>Create a user</h2><p className="admin-card-intro">Choose the company this person can access. The generated login details appear on the right.</p><form onSubmit={submit}><label>Company<select required value={companyId} onChange={(event) => setCompanyId(event.target.value)}><option value="" disabled>Select a company</option>{companies.map((company) => <option key={company.id} value={company.id}>{company.name}</option>)}</select></label><label>Full name<input required autoComplete="name" value={fullName} onChange={(event) => setFullName(event.target.value)} placeholder="Juan Schubert" /></label><button className="button button-primary" disabled={saving || !companyId}>{saving ? "Creating user…" : "Create user"}<span className="button-arrow" aria-hidden="true"/></button>{error && <p className="error" aria-live="polite">{error}</p>}</form><p className="admin-note">The login ID will look like <code>first.last@animaradar.com</code>. It is used only to sign in to AnimaRadar.</p></section><section className="panel credential-panel">{credentials ? <><h2>Login details for {credentials.full_name}</h2><div className="credential-warning">Copy these details now. The temporary password is shown only on this screen.</div><dl><div><dt>Login ID</dt><dd>{credentials.login}</dd></div><div><dt>Temporary password</dt><dd>{credentials.temporary_password}</dd></div></dl><button className="button button-primary" onClick={copyCredentials}>{copied ? "Copied" : "Copy login details"}<span className="button-arrow" aria-hidden="true"/></button><p className="admin-note">The user changes the temporary password after the first login.</p></> : <div className="admin-empty"><h2>Login details will appear here</h2><p>Create a user on the left. Then copy the login ID and temporary password and give them directly to that person.</p></div>}</section></div></div></AppShell>;
}
