"use client";

import { FormEvent, useState } from "react";
import AppShell, { SectionHeading } from "@/components/AppShell";

export default function AdminUsersPage() {
  const [fullName, setFullName] = useState(""); const [credential, setCredential] = useState<{ login: string; temporary_password: string; full_name: string } | null>(null); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false); const [copied, setCopied] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(null); setCredential(null); setCopied(false); try { const response = await fetch("/api/admin/users", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ full_name: fullName }) }); const body = await response.json() as { detail?: string; login?: string; temporary_password?: string; full_name?: string }; if (!response.ok || !body.login || !body.temporary_password || !body.full_name) throw new Error(body.detail ?? "User could not be created"); setCredential({ login: body.login, temporary_password: body.temporary_password, full_name: body.full_name }); setFullName(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "User could not be created"); } finally { setSaving(false); } }
  async function copyCredentials() { if (!credential) return; await navigator.clipboard.writeText(`AnimaRadar login\nName: ${credential.full_name}\nLogin-ID: ${credential.login}\nTemporary password: ${credential.temporary_password}`); setCopied(true); }
  return <AppShell><div className="page-toolbar"><SectionHeading eyebrow="Admin / users" title="Provision access, privately." detail="Create internal AnimaRadar accounts without collecting or sending email. The generated password is shown once and is never stored in plaintext." /><span className="feature-status feature-status--ready">Owner only</span></div><div className="admin-layout"><section className="panel admin-create"><p className="eyebrow">Create user</p><h2>Who should enter the radar?</h2><form onSubmit={submit}><label>Full name<input required name="full_name" autoComplete="name" value={fullName} onChange={(event)=>setFullName(event.target.value)} placeholder="e.g. Juan Schubert…" /></label><button className="button button-primary" disabled={saving}>{saving?"Creating access…":"Create internal account"}<span className="button-arrow" aria-hidden="true" /></button>{error&&<p className="error" aria-live="polite">{error}</p>}</form><p className="admin-note">The login ID uses the format <code>first.last@animaradar.com</code>. It is an internal identifier, not a mailbox.</p></section><section className="panel credential-panel">{credential?<><p className="eyebrow">One-time credential view</p><h2>Hand this access to {credential.full_name.split(/\s+/)[0]}.</h2><div className="credential-warning">This password will only be shown here. Copy it before leaving this screen.</div><dl><div><dt>Login-ID</dt><dd>{credential.login}</dd></div><div><dt>Temporary password</dt><dd>{credential.temporary_password}</dd></div></dl><button className="button button-primary" onClick={copyCredentials}>{copied?"Copied":"Copy credentials"}<span className="button-arrow" aria-hidden="true" /></button><p className="admin-note">The user can change this password after signing in. AnimaRadar stores only Supabase’s password hash.</p></>:<><p className="eyebrow">Credential vault</p><h2>No one provisioned in this session.</h2><p>After creating an account, its login ID and temporary password appear here once. Refreshing the page clears the credential view.</p></>}</section></div></AppShell>;
}
