"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import AppShell, { SectionHeading } from "@/components/AppShell";

type Tenant = { id: string; name: string; default_market_lang: string; created_at: string };

export default function CompaniesPage() {
  const [tenants, setTenants] = useState<Tenant[]>([]); const [name, setName] = useState(""); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  async function load() { const response = await fetch("/api/admin/tenants"); const body = await response.json() as { tenants?: Tenant[]; detail?: string }; if (!response.ok) throw new Error(body.detail ?? "Companies could not be loaded"); setTenants(body.tenants ?? []); }
  useEffect(() => { let active = true; fetch("/api/admin/tenants").then(async (response) => { const body = await response.json() as { tenants?: Tenant[]; detail?: string }; if (!response.ok) throw new Error(body.detail ?? "Companies could not be loaded"); if (active) setTenants(body.tenants ?? []); }).catch((cause) => { if (active) setError(cause instanceof Error ? cause.message : "Companies could not be loaded"); }); return () => { active = false; }; }, []);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(null); try { const response = await fetch("/api/admin/tenants", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name }) }); const body = await response.json() as { tenant?: Tenant; detail?: string }; if (!response.ok || !body.tenant) throw new Error(body.detail ?? "Company could not be created"); setTenants((current) => [...current, body.tenant as Tenant]); setName(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "Company could not be created"); } finally { setSaving(false); } }
  return <AppShell><div className="page-toolbar"><SectionHeading eyebrow="Admin / companies" title="Every company, one radar." detail="Create and oversee isolated company workspaces. Each company gets its own Business DNA, scans, prospects and outreach history." /><Link href="/admin/users" className="button button-ghost">Manage team<span className="button-arrow" aria-hidden="true"/></Link></div><div className="admin-layout"><section className="panel admin-create"><p className="eyebrow">New company</p><h2>Add a company workspace.</h2><form onSubmit={submit}><label>Company name<input required value={name} onChange={(event) => setName(event.target.value)} placeholder="e.g. Andes Bloom" /></label><button className="button button-primary" disabled={saving}>{saving ? "Creating…" : "Create company"}<span className="button-arrow" aria-hidden="true"/></button>{error && <p className="error" aria-live="polite">{error}</p>}</form><p className="admin-note">This creates a separate tenant. Data, users and Business DNA remain isolated from every other company.</p></section><section className="panel company-list"><div className="panel-title"><h2>Company directory</h2><span>{tenants.length} workspaces</span></div>{tenants.map((tenant, index) => <div className="company-row" key={tenant.id}><span className="company-index">{String(index + 1).padStart(2, "0")}</span><div><strong>{tenant.name}</strong><small>{tenant.default_market_lang} · created {new Date(tenant.created_at).toLocaleDateString()}</small></div><Link href={`/admin/users?tenant=${tenant.id}` as never}>Manage team ↗</Link></div>)}{!tenants.length && <p className="empty-state">No companies found.</p>}</section></div></AppShell>;
}
