"use client";

import Link from "next/link";
import type { Route } from "next";
import { FormEvent, useEffect, useState } from "react";
import AppShell, { SectionHeading } from "@/components/AppShell";

type Company = { id: string; name: string; default_market_lang: string; created_at: string };

export default function CompaniesPage() {
  const [companies, setCompanies] = useState<Company[]>([]); const [name, setName] = useState(""); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  useEffect(() => { let active = true; fetch("/api/admin/tenants").then(async (response) => { const body = await response.json() as { tenants?: Company[]; detail?: string }; if (!response.ok) throw new Error(body.detail ?? "Companies could not be loaded"); if (active) setCompanies(body.tenants ?? []); }).catch((cause) => { if (active) setError(cause instanceof Error ? cause.message : "Companies could not be loaded"); }); return () => { active = false; }; }, []);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(null); try { const response = await fetch("/api/admin/tenants", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name }) }); const body = await response.json() as { tenant?: Company; detail?: string }; if (!response.ok || !body.tenant) throw new Error(body.detail ?? "Company could not be created"); setCompanies((current) => [...current, body.tenant as Company]); setName(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "Company could not be created"); } finally { setSaving(false); } }
  return <AppShell><div className="admin-page"><div className="page-toolbar"><SectionHeading title="Companies" detail="View every company using AnimaRadar or create a new one." /><Link href={"/admin/users" as Route} className="button button-ghost">View users<span className="button-arrow" aria-hidden="true"/></Link></div><div className="admin-layout"><section className="panel admin-create"><h2>Add a company</h2><p className="admin-card-intro">Each company receives its own separate data area for users, Business DNA, prospects and outreach.</p><form onSubmit={submit}><label>Company name<input required value={name} onChange={(event) => setName(event.target.value)} placeholder="Andes Bloom" /></label><button className="button button-primary" disabled={saving}>{saving ? "Adding company…" : "Add company"}<span className="button-arrow" aria-hidden="true"/></button>{error && <p className="error" aria-live="polite">{error}</p>}</form></section><section className="panel company-list"><div className="panel-title"><h2>All companies</h2><span>{companies.length} total</span></div>{companies.map((company) => <div className="company-row" key={company.id}><span className="company-mark">{company.name.charAt(0).toUpperCase()}</span><div><strong>{company.name}</strong><small>Language: {company.default_market_lang} · Added {new Date(company.created_at).toLocaleDateString()}</small></div><Link href={`/admin/users?tenant=${company.id}` as Route}>Add user<span aria-hidden="true"> ↗</span></Link></div>)}{!companies.length && !error && <div className="empty-state">No companies yet. Add the first company on the left.</div>}</section></div></div></AppShell>;
}
