"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import AppShell, { SectionHeading } from "@/components/AppShell";
import { useLanguage } from "@/components/LanguageProvider";

type Scan = { id: string; status: string; city: string; country: string; radius_m: number; categories: string[]; sources: string[]; counts: Record<string, number>; created_at: string };

export default function RadarPage() {
  const { language, text } = useLanguage();
  const [scans, setScans] = useState<Scan[]>([]); const [loading, setLoading] = useState(true); const [starting, setStarting] = useState(false); const [error, setError] = useState<string | null>(null);
  useEffect(() => { let live = true; fetch("/api/scans", { cache: "no-store" }).then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error(body.detail); if (live) setScans(body.scans ?? []); }).catch((cause) => { if (live) setError(cause instanceof Error ? cause.message : text("Could not load scans", "No se pudieron cargar los escaneos")); }).finally(() => { if (live) setLoading(false); }); return () => { live = false; }; }, [text]);
  async function startScan(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setStarting(true); setError(null); const form = new FormData(event.currentTarget); try { const response = await fetch("/api/scans", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ city: form.get("city"), country: form.get("country"), radius_m: Number(form.get("radius")) * 1000, categories: String(form.get("categories") ?? "").split(",").map((item) => item.trim()).filter(Boolean), sources: ["google_places", "exa"] }) }); const body = await response.json(); if (!response.ok) throw new Error(body.detail); setScans((current) => [body as Scan, ...current]); event.currentTarget.reset(); } catch (cause) { setError(cause instanceof Error ? cause.message : text("Could not start scan", "No se pudo iniciar el escaneo")); } finally { setStarting(false); } }
  return <AppShell><div className="page-toolbar"><SectionHeading eyebrow={text("Radar / scans", "Radar / escaneos")} title={text("Point the lens at your next market.", "Apunta el radar a tu próximo mercado.")} detail={text("Define a real location, radius and categories. The scan is stored only for the active company.", "Define una ubicación, un radio y categorías reales. El escaneo se guarda únicamente para la empresa activa.")} /></div>{error && <p className="error" aria-live="polite">{error}</p>}<div className="radar-layout"><section className="panel scan-builder"><div className="panel-title"><h2>{text("New scan", "Nuevo escaneo")}</h2><span className="feature-status feature-status--ready">Supabase</span></div><form className="settings-fields" onSubmit={startScan}><label>{text("City", "Ciudad")}<input required name="city" placeholder={text("e.g. Quito", "p. ej. Quito")} /></label><label>{text("Country code", "Código de país")}<input required name="country" maxLength={2} placeholder="EC" /></label><label>{text("Radius in km", "Radio en km")}<input required name="radius" type="number" min="1" max="100" defaultValue="15" /></label><label>{text("Business categories", "Categorías de negocio")}<input required name="categories" placeholder={text("hotels, restaurants, agencies", "hoteles, restaurantes, agencias")} /></label><button className="button button-primary" disabled={starting}>{starting ? text("Creating scan…", "Creando escaneo…") : text("Create scan", "Crear escaneo")}<span className="button-arrow"/></button></form></section><section className="panel scan-history"><div className="panel-title"><h2>{text("Scan history", "Historial de escaneos")}</h2><span>{scans.length}</span></div>{loading ? <div className="empty-state">{text("Loading scans…", "Cargando escaneos…")}</div> : scans.length ? scans.map((scan) => <div className="scan-row" key={scan.id}><span className={`status-dot status-dot--${scan.status}`}/><div><strong>{scan.city}, {scan.country}</strong><small>{scan.radius_m / 1000} km · {scan.categories.join(", ") || text("No categories", "Sin categorías")} · {new Date(scan.created_at).toLocaleDateString(language === "es" ? "es-EC" : "en-US")}</small></div><span className="feature-status">{scan.status}</span></div>) : <div className="empty-state empty-state--action"><strong>{text("No scans for this company yet.", "Aún no hay escaneos para esta empresa.")}</strong><p>{text("Complete Business DNA, then create the first market scan here.", "Completa el ADN del negocio y crea aquí el primer escaneo de mercado.")}</p><Link href="/perfil">{text("Open Business DNA", "Abrir ADN del negocio")} ↗</Link></div>}</section></div></AppShell>;
}
